### ISSUE TITLE
多次扫码，识别的条形码内容不一致

### ISSUE THREAD

**Issue by sqixin** [chinachen01/flutter_scan_preview#1]
同一个条形码，多扫码几次，生成的结果会不一致

**Comment by chinachen01** [comment]
不好意思，前段时间比较忙，没有及时回复，我这边反复测试了几次，没有出现你说的现象，我现在重新发了一个版本，在扫描出结果以后会停止扫描，你再试一下呢？

**Comment by sqixin** [comment]
我后来大概知道了，就是用设备本身带的扫一扫也会出现这种情况，这个是小问题，后来我发现了一个更严重的问题。如果扫描一次，跳转到下一个页面，下一个页面再启动扫码功能就不能再扫了
